export type GalleryGroupId = "cargo" | "lifting" | "securing" | "vessels";

export const galleryGroups: { id: GalleryGroupId; title: string; description: string }[] = [
  { id: "cargo", title: "Cargo & condition", description: "Cargo, packaging, vehicles and inspection details." },
  { id: "lifting", title: "Lifting & loading", description: "Project cargo moving between shore, transport and vessel." },
  { id: "securing", title: "Transport & securing", description: "Loads prepared, stowed and secured for their next journey." },
  { id: "vessels", title: "Vessels & small craft", description: "Shipboard scenes, carriers and specialist craft." },
];

export type GalleryPhoto = {
  id: string;
  src: string;
  alt: string;
  title: string;
  description: string;
  category: string;
  serviceId: string;
  group: GalleryGroupId;
};

export const galleryPhotos: GalleryPhoto[] = [
  { id: "cargo-steel-original", src: "/gallery-service4.jpeg", alt: "Workers examining stacks of steel cargo.", title: "Steel cargo inspection", description: "Stacked steel sections and survey personnel on site.", category: "Cargo survey", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-copper", src: "/gallery/cargo-copper-sheets.jpg", alt: "Surveyor examining bundled copper sheets in a warehouse.", title: "Copper sheet inspection", description: "Bundled metal cargo examined in storage.", category: "Cargo survey", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-damage", src: "/gallery/cargo-cars.jpg", alt: "Surveyor pointing to the rear of a white vehicle.", title: "Vehicle condition inspection", description: "A close look at a vehicle's rear body panel.", category: "Vehicle survey", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-pallets", src: "/gallery/marine7.jpg", alt: "Surveyor beside damaged wooden pallets and bagged cargo along a road.", title: "Cargo and pallet condition", description: "Survey work beside road transport and displaced pallets.", category: "Cargo survey", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-pallets-detail", src: "/gallery/g8.jpg", alt: "Small archival view of a surveyor beside pallets and bagged cargo.", title: "Road cargo archive", description: "An archival view from the roadside cargo inspection.", category: "Field archive", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-steel-detail", src: "/gallery/g12.jpg", alt: "Surveyor inspecting the end of a steel coil.", title: "Steel coil inspection", description: "A close inspection of coiled metal cargo.", category: "Cargo survey", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-tyres", src: "/gallery/marine8.jpg", alt: "Large industrial tyres secured vertically on a flatbed trailer.", title: "Oversize tyre cargo", description: "Industrial tyres on a road transport trailer.", category: "Project cargo", serviceId: "lashing-container", group: "cargo" },
  { id: "draft-measurement", src: "/gallery/20230409_160319_resized.jpg", alt: "Long rows of steel pipes stored at a port.", title: "Pipe cargo at port", description: "Rows of pipes awaiting onward handling.", category: "Cargo quantity", serviceId: "draft-measurement", group: "cargo" },
  { id: "cargo-steel-hold", src: "/gallery/20180828_183828.jpg", alt: "Steel coils packed in rows inside a ship's hold.", title: "Steel coils in the hold", description: "A broad view of coiled steel stowage.", category: "Cargo stowage", serviceId: "discharge-loading", group: "cargo" },
  { id: "cargo-fruit", src: "/gallery/20210626_092431_resized.jpg", alt: "Stacked cartons of fresh fruit in a cargo facility.", title: "Fresh produce cargo", description: "Fruit cartons prepared in a cargo facility.", category: "Perishable cargo", serviceId: "cargo-damage", group: "cargo" },
  { id: "cargo-container-inspection", src: "/gallery/container-inspection.jpg", alt: "Surveyor photographing the doors of a freight container.", title: "Container exterior inspection", description: "Documenting container condition at a facility.", category: "Container survey", serviceId: "lashing-container", group: "cargo" },
  { id: "cargo-large-coils", src: "/gallery/marine9.jpg", alt: "Surveyor beside a row of very large covered industrial coils.", title: "Large coil inspection", description: "Oversize coils lined up at a storage yard.", category: "Cargo survey", serviceId: "cargo-damage", group: "cargo" },

  { id: "marine-warranty", src: "/gallery-service1.jpeg", alt: "Large industrial equipment suspended above a vessel deck during a heavy lift.", title: "Heavy lift at sea", description: "A large module suspended above the vessel deck.", category: "Marine operation", serviceId: "marine-warranty", group: "lifting" },
  { id: "lifting-module-archive", src: "/gallery/marine1.jpg", alt: "Archival view of a large industrial module suspended above a vessel deck.", title: "Heavy lift archive", description: "A second supplied image of the vessel deck lift.", category: "Field archive", serviceId: "marine-warranty", group: "lifting" },
  { id: "discharge-loading", src: "/gallery-service3.jpeg", alt: "Crane lifting cylindrical project cargo at a port at night.", title: "Night-time cargo loading", description: "Cylindrical project cargo raised from a trailer.", category: "Loading operation", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-cylinder", src: "/gallery/marine6.jpg", alt: "Long cylindrical industrial cargo being lifted beside a vessel.", title: "Cylindrical project cargo", description: "A crane lift beside the ship's side.", category: "Heavy lift", serviceId: "marine-warranty", group: "lifting" },
  { id: "lifting-covered-trailer", src: "/gallery/marine5.jpg", alt: "Covered industrial cargo suspended above a heavy transport trailer.", title: "Covered load over trailer", description: "Project cargo positioned above a multi-axle trailer.", category: "Heavy lift", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-covered-ship", src: "/gallery/marine4.jpg", alt: "Covered industrial cargo on a transport trailer beside a ship.", title: "Covered project cargo", description: "A large protected load alongside the vessel.", category: "Project cargo", serviceId: "marine-warranty", group: "lifting" },
  { id: "lifting-covered-suspended", src: "/gallery/marine3.jpg", alt: "Covered rectangular cargo suspended over a multi-axle trailer beside a vessel.", title: "Project cargo transfer", description: "A wrapped unit moving between ship and shore transport.", category: "Heavy lift", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-orange", src: "/gallery/marine2.jpg", alt: "Orange wrapped cargo suspended above an open ship hold.", title: "Wrapped cargo over hold", description: "A protected unit raised above the cargo hold.", category: "Loading operation", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-cable-drum", src: "/gallery/cable-drum-hold.jpg", alt: "Large cable drum suspended over steel coils in a ship hold.", title: "Cable drum in the hold", description: "A cable reel positioned over other cargo.", category: "Heavy lift", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-cable-reel-archive", src: "/gallery/16.jpg", alt: "Large blue cable reel suspended above a vessel hold.", title: "Cable reel lift", description: "A reel raised at the ship's open hold.", category: "Heavy lift", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-pipes", src: "/gallery/20230223_153058_resized.jpg", alt: "Two long pipes suspended by crane above a vessel hold.", title: "Pipe loading", description: "Long pipe cargo suspended over the hold.", category: "Loading operation", serviceId: "discharge-loading", group: "lifting" },
  { id: "lifting-tank", src: "/gallery/20220625_150010_resized.jpg", alt: "Large cylindrical tank rigged to a spreader bar beside a vessel.", title: "Tank lifting arrangement", description: "A cylindrical unit beneath lifting gear at the quayside.", category: "Heavy lift", serviceId: "marine-warranty", group: "lifting" },
  { id: "lifting-heavy-2018", src: "/gallery/20180505_102822.jpg", alt: "Covered industrial equipment suspended above a red multi-axle trailer.", title: "Quayside heavy lift", description: "A protected unit being lowered to transport equipment.", category: "Heavy lift", serviceId: "marine-warranty", group: "lifting" },
  { id: "lifting-steel-coil", src: "/gallery/marine12.jpg", alt: "Large steel coil suspended by crane above a transport trailer.", title: "Steel coil lift", description: "Coiled steel raised above road transport.", category: "Loading operation", serviceId: "discharge-loading", group: "lifting" },

  { id: "lashing-container", src: "/gallery-service2.jpeg", alt: "Large industrial cargo secured with chains on a barge.", title: "Secured project cargo", description: "Industrial equipment secured for transport on a barge.", category: "Cargo securing", serviceId: "lashing-container", group: "securing" },
  { id: "securing-machine", src: "/gallery/marine11.jpg", alt: "Large yellow industrial machine secured on an open transport platform.", title: "Machine on transport platform", description: "Project equipment positioned for road movement.", category: "Project cargo", serviceId: "lashing-container", group: "securing" },
  { id: "securing-reels", src: "/gallery/20170107_145454.jpg", alt: "Large blue cable reels fastened on transport trailers.", title: "Cable reels in transit", description: "Oversize reels secured on transport frames.", category: "Cargo securing", serviceId: "lashing-container", group: "securing" },
  { id: "securing-tank-trailer", src: "/gallery/20220625_141346_resized.jpg", alt: "Cylindrical tank on a trailer beside a cargo ship.", title: "Tank on quayside trailer", description: "A cylindrical unit prepared beside the vessel.", category: "Project transport", serviceId: "lashing-container", group: "securing" },
  { id: "securing-boat-trailer", src: "/gallery/20230203_073349_resized.jpg", alt: "Wrapped boat strapped to a flatbed trailer.", title: "Small craft secured for road", description: "A protected boat fastened to a transport trailer.", category: "Cargo securing", serviceId: "lashing-container", group: "securing" },
  { id: "securing-blue-equipment", src: "/gallery/20210811_121405_resized.jpg", alt: "Blue covered industrial equipment inside a cargo facility.", title: "Protected industrial unit", description: "A covered unit positioned inside a facility.", category: "Project cargo", serviceId: "cargo-damage", group: "securing" },
  { id: "securing-reefer", src: "/gallery/20210626_094358_resized.jpg", alt: "Refrigerated freight container on a trailer at a warehouse bay.", title: "Reefer container", description: "A refrigerated container at the loading bay.", category: "Container survey", serviceId: "lashing-container", group: "securing" },
  { id: "securing-helicopter", src: "/gallery/20180219_111640.jpg", alt: "Red and white helicopter fuselage on a freight platform.", title: "Helicopter fuselage transport", description: "An aircraft fuselage on a freight platform.", category: "Special cargo", serviceId: "specialist-inspections", group: "securing" },
  { id: "securing-helicopter-detail", src: "/gallery/20180215_102926.jpg", alt: "Close view of a red and white helicopter fuselage in storage.", title: "Helicopter fuselage detail", description: "A close view of the stored aircraft body.", category: "Special cargo", serviceId: "specialist-inspections", group: "securing" },
  { id: "securing-cargo-banner", src: "/gallery/cargo-banner.jpg", alt: "Composite image of cargo crates in a ship hold and a wrapped wind turbine component on a trailer.", title: "Project cargo archive", description: "An archival composite of ship and road cargo.", category: "Field archive", serviceId: "lashing-container", group: "securing" },

  { id: "charter-bunker", src: "/gallery/20180831_154441.jpg", alt: "Green cargo ship moored at a quayside beneath its deck cranes.", title: "Cargo vessel at berth", description: "A ship alongside the working quay.", category: "Vessel", serviceId: "charter-bunker", group: "vessels" },
  { id: "hull-incidents", src: "/gallery/20230307_143129_resized.jpg", alt: "Long industrial structure lashed on the deck of a cargo vessel.", title: "Vessel deck cargo", description: "A view along the working deck toward the bridge.", category: "Vessel", serviceId: "hull-incidents", group: "vessels" },
  { id: "specialist-inspections", src: "/gallery/20230222_092222_resized.jpg", alt: "Wood-finish motorboat moored on calm water beside a quay.", title: "Small craft at the quay", description: "A leisure craft alongside the waterfront.", category: "Small craft", serviceId: "specialist-inspections", group: "vessels" },
  { id: "vessel-small-craft-lift", src: "/gallery/20230203_110838_resized.jpg", alt: "Small motorboat suspended by lifting straps above the water.", title: "Small craft lift", description: "A boat raised between quay and water.", category: "Small craft", serviceId: "specialist-inspections", group: "vessels" },
  { id: "vessel-roro-loading", src: "/gallery/roro-loading.jpg", alt: "Vehicles moving at the open ramp of a roll-on roll-off ship.", title: "Vehicle carrier loading", description: "Vehicles at a roll-on roll-off vessel ramp.", category: "Vessel operations", serviceId: "discharge-loading", group: "vessels" },
  { id: "vessel-car-carrier", src: "/gallery/car-carrier.jpg", alt: "Large car carrier ship with parked vehicles alongside.", title: "Car carrier", description: "A car carrier alongside rows of vehicles.", category: "Vessel", serviceId: "discharge-loading", group: "vessels" },
];
